application: cloudcomputing553
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: numpy
  version: "1.6.1"

- name: jinja2
  version: latest

